### ISSUE TITLE
JavaCUP

### ISSUE THREAD

**Issue by wejeus** [kanelbulle/cortado#1]
java-cup-11a-runtime.jar verkar inte funka, var kom den ifrån? Ersatt med http://www2.cs.tum.edu/projects/cup/java-cup-11a.jar

**Comment by kanelbulle** [comment]
Den kom från samma sida (http://www2.cs.tum.edu/projects/cup/java-cup-11a-runtime.jar). Jag är lite osäker på vad skillnaden mellan runtime och vanlig är..

**Comment by wejeus** [comment]
Ok, vi kanske upptäcker det när vi väl lärt oss cup :å

**Comment by wejeus** [comment]
Saknad funktionalitet:
extends på klasser, (initiering av variabler?), retur void typ på main method.

**Comment by kanelbulle** [comment]
java-cup11a-runtime ersatt med java-cup11a.jar

**Comment by wejeus** [comment]
När det gäller listor som skapas/returneras av grammatiken så adresseras dessa via globals, skulle kunna ändra till att skicka med via parametrar ist..
