### ISSUE TITLE
while(..) and if(..) dont parse

### ISSUE THREAD

**Issue by wejeus** [kanelbulle/cortado#12]
NO PARSE FOR YOU ! På ovanstående

**Comment by kanelbulle** [comment]
Visa exakta koden du försöker köra plz

**Comment by wejeus** [comment]
class Superklasse {
    public static void main(String[] args) {

```
}
```

}

class TestClass {
    public int fnurf(int ss) {

```
    int j;
    j = 89;

    if(j == 89) {
        int a;
        a = 10;
        j = a;
    } else {
        j = 100;
    }
    return 1;
}
```

}

**Comment by kanelbulle** [comment]
du får inte deklarera variabler inuti if-satsen!

**Comment by wejeus** [comment]
Goddammit minijava! =) Sorry for being stupid..

**Comment by kanelbulle** [comment]
:)

**Comment by wejeus** [comment]
STILL NO PARSE! Eller har jag missat något annat...?

class TestClass {
    public int fnurf(int ss) {
        int j;
        j = 1;

```
    if (j == 1) {
        j = 10;
    } else {
        j = 100;
    }

    return j;
}
```

}

**Comment by kanelbulle** [comment]
Ja, vi har inte "==" :D

Det här funkar:

``` java

class Superklasse {
    public static void main(String[] args) {

    }
}

class TestClass {
    public int fnurf(int ss) {
        int j;
        j = 1;

        if (j < 1) {
            j = 10;
        } else {
            j = 100;
        }

        return j;
    }
}
```

**Comment by wejeus** [comment]
Men gud, nu går jag hem och drar nått gammalt över mig.
