### ISSUE TITLE
Grammatik

### ISSUE THREAD

**Issue by wejeus** [kanelbulle/cortado#2]
Saknad funktionalitet:
extends på klasser, (initiering av variabler?), retur void typ på main method.

**Comment by wejeus** [comment]
När det gäller listor som skapas/returneras av grammatiken så adresseras dessa via globals, skulle kunna ändra till att skicka med via parametrar ist..

**Comment by kanelbulle** [comment]
- extends finns ej i grundgrammatiken
- initiering av variabler går ej att göra på parsernivå då det är giltigt att senarelägga initiering, du kan ju t ex göra:
  Object o;
  bla bla bla for loop, metodanrop och annat om man vill
  o = null;
- Hm, hur kan man skicka med dom som parametrar? Problemet är att när en terminal ska returnera något, så vet den inte vilken lista den ska sättas in i. Var skulle parametrarna skickas in?

**Comment by kanelbulle** [comment]
Ok, enligt projektsidan behöver vi inte kolla variabelinitialisering alls:
- (*) Actually, you do not need to check that variables are initialized, so some legal Minijava programs with undefined behaviour will in fact not be legal Java programs.

**Comment by wejeus** [comment]
Ok. Såg att det skelett vi importerade hade en klass som hette 'ClassDeclExtended' såg jag antog att vi skulle implementera det med ;)

**Comment by kanelbulle** [comment]
Ah, yes, det är en extension. Den får ligga kvar där ifall vi bestämmer oss för att göra den!
