### ISSUE TITLE
Type checking system

### ISSUE THREAD

**Issue by wejeus** [kanelbulle/cortado#8]
Traversera syntax trädet och utför type checking på:

(saxat från dragons book)

-- constants --
obviously, every constant has an associated type.  A scanner tells 
us these types as well as the associated lexeme. 

-- variables --
all variables (global, local, and instance) must have a declared 
type of one of the base types or the supported compound types.   

-- functions --
functions have a return type, and each parameter in the function 
definition has a type, as does each argument in a function call. 

-- expressions --
an expression can be a constant, variable, function call, or some 
operator (binary or unary) applied to expressions.  Each of the 
various expressions have a type based on the type of the constant, 
variable, return type of the function, or type of operand

**Comment by kanelbulle** [comment]
Klart
